### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by raphaelbastide** [thedesignoffice/babybindery#1]
I am curious about how to use Babybindery, a bit of documentation is missing.

**Comment by cathschmidt** [comment]
You're right! We're working on documentation currently. We'll be building a microsite. README etc will also be updated to better reflect what this actually does. Check back in two weeks or look at TODO.

Essentially — it's a Jekyll static site template that flows all content into a print layout using a js implementation of css regions. Page numbers, footnotes with link urls, and a few other "bookish" goodies are affixed to the  print layout after flow.
