### ISSUE TITLE
custom.css file

### ISSUE THREAD

**Issue by ltwp** [thedesignoffice/babybindery#10]
With prompts for certain things. Perhaps we can use CSS variables.

**Comment by jcaserta** [comment]
This might fall under the issue I just created. Will leave this as an open issue for now, but I would suggest not forking under this issue until issue 11 is closed.

**Comment by ltwp** [comment]
I think this and #11 are related but this is separate—the custom css file will serve as an entrypoint to edit much more than just page dimension, whereas that one is a very structural issue.
