### ISSUE TITLE
GIF Handling?

### ISSUE THREAD

**Issue by ltwp** [thedesignoffice/babybindery#30]
On print, should GIFs be frozen at their first frame?

**Comment by jcaserta** [comment]
the way bindery did it was nice... it would swap out a png for the gifs ... allows for higher resolutions as well... .if there is no png, can't recall if it breaks ... maybe look at bindery implementation? I have a post of gifs that you can test on.

**Comment by ltwp** [comment]
Yeah, the bindery implementation expected a png of the same name alongside every GIF. 
I'll check for that and if nothing found I'll try to see if we can fix a frame of the GIFs.

**Comment by ltwp** [comment]
Tried using this but some conflicts & loading issues :( https://github.com/ctrl-freaks/freezeframe.js

**Comment by ltwp** [comment]
Also sticking this into book.css
```
-webkit-animation-play-state: paused !important;
-moz-animation-play-state: paused !important;
-o-animation-play-state: paused !important;
animation-play-state: paused !important;
```

Doesn't seem to work.

**Comment by ltwp** [comment]
Scrapping. Looks like not possible to freeze GIFs w/o server-side work for now. see commit 201c1ab862607473baf2fb72ae73f6c848e33205
