### ISSUE TITLE
Clipping long link URLs

### ISSUE THREAD

**Issue by ltwp** [thedesignoffice/babybindery#31]
Clip URLs at 30 characters and append ellipses, perhaps? 
Would love your thoughts @jcaserta

**Comment by jcaserta** [comment]
Firstly, would be good to not have "http://" in the printed URL. The bummer about truncation is that the printed work is meant to be the archival work... the copy of record. So if the URL is truncated, we lose that. The web version of a book ideally is still active, but not necessarily. Author should ideally use a URL shortner (itself an archival no-no)... but author can decide. So I'd say, let's strip the http:// and then run the whole url (maybe truncate if crazy long... like some of the google maps urls... at 75 characters)

**Comment by ltwp** [comment]
OK, sounds good!

**Comment by ltwp** [comment]
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/ leaving this here for future reference
