### ISSUE TITLE
CSS columns? For two-column layout

### ISSUE THREAD

**Issue by cathschmidt** [thedesignoffice/babybindery#5]
Should the two column layout use css columns instead of two page objects

**Comment by cathschmidt** [comment]
![bauhaus](https://i.ytimg.com/vi/fD2LM_lYTKg/hqdefault.jpg)

**Comment by bjornmeansbear** [comment]
Just coming across this project. I've experimented with similar things, and it depends on how you "print" ... In my experience WebKit browsers currently turn CSS columns into 1 column when sent to print. Firefox (and phantom.js) are what I can get to print CSS multi columns correctly.
