### ISSUE TITLE
Links as Endnotes

### ISSUE THREAD

**Issue by ltwp** [thedesignoffice/babybindery#9]

**Comment by ltwp** [comment]
The reason this isn't already a closed issue is we need a numbering system to index the links!

**Comment by jcaserta** [comment]
Perhaps broadening this issue to "endnotes" more generally is a good thing. Should an html tag (cite) be used to generate an end note (number added :after the tag with meta data appearing at end of post). The web and the book version could act similarly, perhaps a rollover state on the web page.

**Comment by ltwp** [comment]
https://stackoverflow.com/questions/25060352/show-pseudo-element-but-not-parent-element
